### ISSUE TITLE
Research and explain Boolean type

### ISSUE THREAD

**Issue by razcore-rad** [JordanMartinez/purescript-jordans-reference#139]
## Context

1. Indicate the affected section (i.e. top-level folder)
I'm not sure where it would go

2. Indicate what kind of issue this is
Enhancement = a new idea that can be documented/filed

3. If it applies, indicate the file to which you are referring using non-numerical-ordering names

## Body
As it stands, purescript has a `Boolean` type with `true` & `false` values. Beginners such as myself, especially ones coming from haskell where there's the `data Bool = True | False` definition, might wonder where's `True` & `False` in purescript. Or why they're not present. I don't know the full history behind it but I assume it has to do with purescript being so tightly linked with javascript. It can definitely be a point of confusion as one would expect all constructors to start with a capital letters and this being such a simple data type one wouldn't expect literal values for it, or at least it's a bit of a discord compared to basic types.

**Comment by JordanMartinez** [comment]
> psc-package is originally phil and others' project

Yeah... that's a good question :sweat_smile: Haha! 

I'm coming from a Java background and the `true/false` values are lower-cased. So, this issue could be solved in one of two ways:
- Add a "Differences from Haskell" file
- Explain how the Javascript backend influenced the syntax of the language (Technically, PureScript could compile to C and Swift depending on which backend one uses.)

I think I like the 'Haskell Differences' idea better because it's the only language I know of that uppercases the `true/false` values.

Thoughts?

**Comment by thomashoneyman** [comment]
You may simply want to link to this:
https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md

**Comment by JordanMartinez** [comment]
@thomashoneyman True. I can't recall whether I'd already linked to that specific page or not (I'm guessing not). However, this particular issue can either be solved by updating that repo's page to include that True/False difference or we restate it here. Either way splits the content into two places.

**Comment by razcore-rad** [comment]
I don't think you linked to the differences, at least I can't remember either. I think we should update that repo's page + offer a short javascript influence explanation in this repo which would talk about why such a simple data type would need literal values instead of the regular constructors.

**Comment by JordanMartinez** [comment]
Either way, we should link to that page. My question is, where should that link ideally appear? In the `Getting Started` folder, I presume?

> offer a short javascript influence explanation in this repo which would talk about why such a simple data type would need literal values instead of the regular constructors.

Seems like there should be a `Backends` section/folder, perhaps in the Getting Started folder.

**Comment by razcore-rad** [comment]
I think the `Backends` idea is fine, placed in `Getting Started`. If you think you want to roll your own 2cents about the literal values `true`/`fasle` I think those might be better off in `Syntax`.

**Comment by JordanMartinez** [comment]
@razcore-art Would you be willing to submit a PR that includes a small snippet for Haskellers in the Syntax part that explains Boolean's quirk? I'll submit a separate PR that includes the link to the Differences from Haskell page, though if you want to include that in a PR, go for it. I was going to put it in its own section in the `Getting Started/Other Imporant Info.md`.

**Comment by razcore-rad** [comment]
I can try and see what happens, you know you're giving this task to a total
beginner :). I can link with Purescript differences from Haskell as well.

**Comment by JordanMartinez** [comment]
> you know you're giving this task to a total beginner

And...? Haha! This whole repo is my understanding of PureScript, any and all of which could be wrong, haha! If you happen to contribute something that is wrong, you're in good company. We can learn together.

Still, I don't think this particular issue is that difficult. You're basically saying, "In Haskell, you write `True` and in PureScript, you write `true`. Why? Because of the influence of Javascript. Why not change it? Because backwards compatibility and ecosystem stability, etc."

> I can link with Purescript differences from Haskell as well.

Ok, thanks!

**Comment by razcore-rad** [comment]
some notes on research:

a bit of confusion, seems like I'm not the only one: https://github.com/purescript/purescript/issues/842, especially this comment https://github.com/purescript/purescript/issues/842#issuecomment-143492100
in essence: *built-in types aren't ADTs and so it follows they don't have constructors in the regular FP style*
explanation in purescript by example: https://leanpub.com/purescript/read#leanpub-auto-simple-types
prim module: https://pursuit.purescript.org/builtins/docs/Prim#t:Boolean - not much explanation, just that we use `true`/`false` literal values

**Comment by JordanMartinez** [comment]
> some notes on research:

Mm... that makes a lot more sense.

Rather than using `Boolean` as the example type that help teach type-level programming's syntax, what if we used a type that works just like Boolean but gets around this suprising-capitalization-syntax issue: `YesNo`?

**Comment by razcore-rad** [comment]
`YesNo` is good

**Comment by JordanMartinez** [comment]
Mind submitting a PR that changes that?

**Comment by razcore-rad** [comment]
I can take care of that sure.

**Comment by JordanMartinez** [comment]
@razcore-art Thanks! And just to make sure this gets done instead of turning into 
a "yeah I'll submit a PR. \*1 year passes w/o a PR\*," I'll wait for a week. If it's not done by then, I'll do it.

**Comment by razcore-rad** [comment]
Yes, that's acceptable :)

**Comment by JordanMartinez** [comment]
I've linked to the documentation repo and also a PDF that I also found quite helpful and descriptive (see #156). What are the next actions for this issue?

**Comment by razcore-rad** [comment]
Your low maintenance work on this repo is far more active than I initially thought :). Yes, I just need to explain in writing why purescript `Boolean` uses literal `true/false` values rather than `True/False` constructors and we'll be good to close this issue. I'll get to it today

**Comment by JordanMartinez** [comment]
Perhaps I should define "low maintenance": if it requires me to do additional work for a new release each time (e.g. something more than submit development PR on latestRelease branch, summarize new changes, define new tag and release on GH), then it's no longer low maintenance.

If it's fixing bugs or adding new content, I just consider that learning.

> I'll get to it today

Excellent!

**Comment by razcore-rad** [comment]
Well I didn't get to it that day :) but I'm getting to it right now

**Comment by AntC2** [comment]
> You may simply want to link to this: https://github.com/purescript/documentation/blob/master/language/Differences-from-Haskell.md

Looks like nobody did mention `true/false` vs `True/False` on that page. That would have saved me some consternation, coming from Haskell.

The world doesn't seem to have blown up if I declare 

    data Bool = False | True
    derive instance eqBool :: Eq Bool 
    derive instance ordBool :: Ord Bool 

And a `Show` instance; and some conversion functions.

**Comment by JordanMartinez** [comment]
Can you open an issue on the documentaiton repo?
