### ISSUE TITLE
Constraint Kinds example

### ISSUE THREAD

**Issue by linearray** [JordanMartinez/purescript-jordans-reference#228]
## Context

Section:
  Design Pattern

Issue Type:
  Bug

File:
  - Design Patterns/Simulating Constraint Kinds.md

## Body

Using PS 0.12.2 I cannot compile the example given. At the use site of the type synonym I get the error   `Unable to parse module:
  unexpected comma in constraints.`

There's also the matter of using `MyMonad` instead of `WithMyMonad`.

After some trial and error and applying compiler suggestions, I ended up with this diff that at least compiles: https://gist.github.com/linearray/239be7b3fc9cd35548f7ccc76cc79854

I also think the file needs an example for `f` or `g`, because I was unable to come up with one, but maybe that's because I mutilated the types.

**Comment by JordanMartinez** [comment]
Thanks for opening the issue. I think the heart of this issue is not having CI build this folder's examples as well, as that's why I didn't catch this earlier.

Also, the repo is not yet updated to `0.12.2` yet. See #218 for context.

**Comment by JordanMartinez** [comment]
I'm going to remove this from the 'design patterns' folder in a future update. Having a better understanding of this, we really just need constraint kinds. The simulation, as you provided in your gist, probably isn't worth it...
