### ISSUE TITLE
Ado notation breaks docs

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#28]
See purescript/purescript#3414

**Comment by JordanMartinez** [comment]
This has now been documented.

**Comment by hdgarrood** [comment]
This will be fixed as of the next release (scheduled 24 Feb).

**Comment by JordanMartinez** [comment]
In a `0.12.3` release? Nice!

**Comment by hdgarrood** [comment]
Most likely, yes. (I suppose it’s also possible that the next release will include some breaking changes and therefore it would be 0.13.0, but I don’t think that’s very likely at all)

**Comment by JordanMartinez** [comment]
Ok. Good to know.
