### ISSUE TITLE
Document concise record creation syntax

### ISSUE THREAD

**Issue by jhrcek** [JordanMartinez/purescript-jordans-reference#333]
Section:
  Syntax/Basic-Syntax/Data-and-Functions/Records

Issue Type:
  Enhancement

Folder/File(s):
?

Please document record creation syntax (don't know how it's called) which makes it possible to create records like

```purescript 
rec =
    { field1
    , field2
    , field3
    }
  where
    field1 = "abc"
    field2 = 1
    field3 = true
```

As mentioned in https://github.com/JordanMartinez/learn-halogen/pull/16#issue-280844858

**Comment by JordanMartinez** [comment]
Thanks.

The other aspect of this issue is something like this:
```purescript
-- notice how 'b' is never mentioned here in our record pattern matching
f :: { a :: String, b :: String } -> String
f { a } = a
```

**Comment by JordanMartinez** [comment]
> The other aspect of this issue is something like this:

Turns out I already cover this at the bottom of the `Basic Syntax` file in the Record folder. Had I known that, i would have included this in the latest release (v0.15.0)

**Comment by JordanMartinez** [comment]
This has been added in latest commit pushed to the `development` branch.

**Comment by jhrcek** [comment]
Nice explanation. Thanks!
