### ISSUE TITLE
Highlight GitHub's global code search functionality

### ISSUE THREAD

**Issue by kurtmilam** [JordanMartinez/purescript-jordans-reference#339]
## Context

Section:
  Getting Started

Issue Type:
  Enhancement

Folder/File:
- "Getting Started/Other Important Info.md"

## Body

GitHub's global search in code feature can be an excellent way to find implementation examples of various PureScript libraries.

Example link to code search for [purescript-quickcheck-laws](https://github.com/search?q=in%3Afile+%22purescript-quickcheck-laws%22&type=Code) (194 results at this time).

Here's GitHub's page on [searching code](https://help.github.com/en/articles/searching-code) with more details.

**Comment by JordanMartinez** [comment]
Thanks!

**Comment by JordanMartinez** [comment]
How's this?
https://github.com/JordanMartinez/purescript-jordans-reference/commit/de118662b69650906e599aee47d1a597fb17c08f

**Comment by kurtmilam** [comment]
That looks great!
