### ISSUE TITLE
Wrong syntax in code example

### ISSUE THREAD

**Issue by ahnwarez** [JordanMartinez/purescript-jordans-reference#357]
The below code snippet is taken from [here](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/21-Hello-World/08-Application-Structure/src/01-Monads-and-Effects.md#composing-monads)

Currently, it is `Box "5"` but it should be `Box "4"`

```bind :: forall a. f   a -> ( a    -> f   b)           -> f    b
bind :: forall a. Box a -> ( a    -> Box b         )  -> Box  b
bind             (Box 4)   (\four -> Box (show four)) == Box "4"
```

**Comment by JordanMartinez** [comment]
Oh, whoops! Thanks for pointing that out!
