### ISSUE TITLE
Fix broken link: Difference from Haskell.pdf

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#390]
http://code.adriansieber.com/adrian/adriansieber-com/src/branch/master/posts/_2018-11-01_introduction_to_purescript_for_haskell_developers/main_light.pdf

This is the correct link for a link in the Getting Started/Other Important Info.md file

**Comment by toraritte** [comment]
This link is also dead now, and couldn't find it anywhere else either... It is also not on [archive.org](https://archive.org/).
