### ISSUE TITLE
Alternate workflow suggestion in REPL reload section

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-jordans-reference#400]
```
Section:
  Getting Started

Issue Type:
  Enhancement

Folder/File(s):
  - Getting Started/The REPL.md
```

https://github.com/JordanMartinez/purescript-jordans-reference/blob/development/00-Getting-Started/03-The-REPL.md#reload

The end of this section may be a good place to note that these `Multiple value declarations` errors can be avoided if using a workflow where all commands are placed in a separate module / file, which is then reloaded.

**Comment by JordanMartinez** [comment]
> The end of this section may be a good place to note that these Multiple value declarations errors can be avoided if using a workflow where all commands are placed in a separate module / file, which is then reloaded.

Good point. My initial assumption was that one would only use the REPL for getting started with the language. However, this repo is also a reference work and the REPL can be used as a test bed for some ideas and whatnot, so your suggestion is valid.

If you're up for it, please submit a PR and I'll merge it.

**Comment by JordanMartinez** [comment]
Fixed in 6fe290f86c71b616a196b21eedc9515c14bd2205

Let me know if you think that should be worded differently.

**Comment by milesfrain** [comment]
> Let me know if you think that should be worded differently.

Some minor typos in the original, but thinking something like the following:

---------------------

3. define your code in a file (as a module) and import that module into your REPL session. Any edits made to this file are picked-up upon a REPL reload.

Create a file containing your REPL script:
```
-- MyModule.file
module MyModule where

import Prelude

add1 = (\x -> x + 1)
times2 = (\x -> x * 3) -- This typo will be fixed later
```

Load script into the REPL:
```
> import MyModule
> times2 4
12
```

Make any edits to this file. For example, change to `times2 = (\x -> x * 2)`. Save file, then reload in existing REPL session. The `MyModule` import will be remembered.
```
> :reload
> times2 4
8
```

**Comment by JordanMartinez** [comment]
Ahh, yeah that is much clearer. Mind submitting that as a PR to the
development branch? Then it'll be included in next release.

I likely won't respond until my lunch break or after I get off work.

**Comment by milesfrain** [comment]
> Mind submitting that as a PR to the development branch?

PR in #404
