### ISSUE TITLE
a type error in A Magical Monad

### ISSUE THREAD

**Issue by JunYang-tes** [JordanMartinez/purescript-jordans-reference#405]
```
Section:
  Hello World

Issue Type:
  Bug

Folder/File(s):
  - Hello-World/Application-Structure/src/MTL/Implementing-a-Monad-Transformer/Magical-Monad
 
```

In [this](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/21-Hello-World/05-Application-Structure/src/02-MTL/02-Implementing-a-Monad-Transformer/03-A-Magical-Monad.md) file, ` g state` is a monad can't match to `(Tuple  value state2)`

![image](https://user-images.githubusercontent.com/17270099/68813340-7c70cf00-06b0-11ea-96c1-b8e333391193.png)

I guess should change to something like this:

![image](https://user-images.githubusercontent.com/17270099/68813797-efc71080-06b1-11ea-8e02-718ff25c4785.png)

---

It's a wonderful, helpful project. Thanks.👏

**Comment by JordanMartinez** [comment]
Ah! Yeah, that's a mistake on my part.

While I like your suggestion, I think I'd prefer something that breaks each entity down into a step-by-step notion to help clarify what's going on
```purescript
instance functor :: (Monad monad) => Functor (StateT state monad) where
  map :: forall a b
       . (a -> b)
      -> StateT state monad a
      -> StateT state monad b
  map f (StateT g) = StateT (\state -> do
      let monadContainingTuple = g state
      (Tuple value state2) <- monadContainingTuple
      let b = f value
      pure (Tuple b state2)
    )
```

**Comment by JordanMartinez** [comment]
@OuyangQianba Since you discovered this mistake, would you mind submitting a PR to fix it?

**Comment by JunYang-tes** [comment]
@JordanMartinez , Yeah, my pleasure to submit a PR. I'll do it later this day.
