### ISSUE TITLE
Possibly document issues with synonyms in superclass constraints

### ISSUE THREAD

**Issue by jy14898** [JordanMartinez/purescript-jordans-reference#419]
## Context
```
Section:
  Syntax

Issue Type:
  Enhancement/ToResearch

Folder/File(s):
  Syntax/Basic-Syntax/src/TypeClasses-and-Newtypes/Typeclass-Relationships.purs
```
## Body

As per the request from Slack, there is currently a bug in purs which causes type synonyms to not be properly expanded in superclass constraints: https://github.com/purescript/purescript/issues/3734

I encountered the bug when trying to make a 'summarizing' class which adds no new laws/methods. 

The starting code compiles fine as expected:
```purescript
module Bug where

data DataA

class ClassA a
instance classA :: ClassA DataA
```

And the following addition to the above code also works:
```purescript
class (ClassA DataA) <= ClassB a
instance classB :: ClassB a
```

However if we replace `DataA` with a synonym of it in the superclass constraint, it fails:
```purescript
type DataB = DataA
class (ClassA DataB) <= ClassB a
instance classB :: ClassB a
```
with the message:
```

  No type class instance was found for
                    
    Bug.ClassA DataB
                    

while checking that expression #dict ClassA
  has type Record ()
in value declaration classB

```

(Note: My actual use was slightly more complicated, with a shared type variable between the superclass and subclass with fundeps relating the type to others, however it is not needed to reproduce the error)

**Comment by JordanMartinez** [comment]
Thanks for opening an issue.

This will go in the Basic Syntax/Type Classes/Gotchas section.

**Comment by JordanMartinez** [comment]
So, I do have a comment regarding type aliases always failing when used in a type class [here](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/11-Syntax/01-Basic-Syntax/src/03-TypeClasses-and-Newtypes/01-Single-Paramter.purs#L62-L70).

I'm not quite sure what to do with your example because `class (ClassA ConcreteType) => ...` requires a instance of `ClassA` but the instance isn't polymorphic (e.g. `(ClassA a) =>`).

I'm not sure whether you were doing type-level programming. Or whether you wanted to write something like this instead:
```purescript
class ClassB a where
  someFunction :: forall a. ClassA ConcreteType => -- ...
```

Thoughts?

**Comment by jy14898** [comment]
The example was quite simplified (obviously too much for it to make sense now)

Perhaps a better example closer to what I was doing:
```purescript
-- LitSym states that a given interpretation `repr` supports literals of type `a`
-- For example, if we're compiling to JavaScript, we need to be able to turn a into a
-- string that JS can understand (not all types are easily represented as literals in JS)
class LitSym repr a where
  lit :: a -> repr a

-- Example litsym instances
newtype CompileToJS a = JS String
instance intInstance :: LitSym CompileToJS Int where
  lit a = JS $ "(" <> show a <> "|0)" 
instance stringInstance :: LitSym CompileToJS String where
  lit a = JS $ "\"" <> show a <> "\"" 

-- A class summarising JS literal capabilities
class ( LitSym repr String, ... , LitSym repr Int ) <= JSSym repr

-- Examples of instances
instance jsSymToJS :: JSSym CompileToJS
instance jsSymOptimiser :: 
    ( JSSym repr
    ) => JSSym (Optimiser repr)

-- repr polymorphic value which doesn't require all the individual LitSym constraints
-- just the summary
someValues :: forall repr. JSSym repr => { a :: repr Int, b :: repr String } 
someValues = { a: lit 10, b: lit "hello world" }
```

Part of the reason why I got so confused was that my synonym was very similar to the type itself (esp. when I'm tired), so took me a long time to actually parse the error and understand the issue. To clarify, my synonym was on the `a` of the LitSym


The comment on type aliases in instances is slightly different (which isn't a bug, and thus documented/given a proper error message)

**Comment by JordanMartinez** [comment]
Ah... ok. That makes sense.

I think this example could go in one of two places. Either the Syntax folder where I cover some of the Gotchas in type classes or in the Hello World/Debugging folder as this might be a confusing error that arises.

**Comment by kl0tl** [comment]
This compiles on master (ace2bab92379e776477c78b70323bcc131865d19 as of now), it will be fixed in the next release!
