### ISSUE TITLE
Possibly a typo issue for Monad instance implement

### ISSUE THREAD

**Issue by steven-zhc** [JordanMartinez/purescript-jordans-reference#435]
```
Section:
  Hello-World

Issue Type:
  Bug

Folder/File(s):
  - Hello-World/Application-Structure/MTL/Foundations.md/The-Function-Monad.md

```

I think this is a typo. at line 87
```purescript
class Functor (Function input) where
  map :: forall originalOutput newOutput.
         (originalOutput -> newOutput) ->
         Function input originalOutput -> Function input newOutput
  map originalToNew f = (\input ->
    let originalOutput = f argument
    in {- remaining body of function -} )
```
the `argument` should be replace by `input`

```purescript
map originalToNew f = (\input ->
    let originalOutput = f input
    in {- remaining body of function -} )
```

the same problem at line 98
```purescript
class Functor (Function input) where
  map :: forall originalOutput newOutput.
         (originalOutput -> newOutput) ->
         Function input originalOutput -> Function input newOutput
  map originalToNew f = (\input ->
    let originalOutput = f argument
    in originalToNew originalOutput)
```

and as a newbie for Purescript or type class. In the beginning, I confused the name between class/declaration and function implementation. Such as in the above snippet, the `input` term in class 
means a type of function argument, but in the lambda expression, it's a real value that will be passed in.
Could we use different name? or add a comment here. that's will much easier to understand the `Function` monad

**Comment by JordanMartinez** [comment]
Oo, good catch! That should be `input`, not `argument`.

Hmm... What if we changed it to `InputType` and `OutputType` when referring to the types of the function's input/output and `inputValue` and `outputValue` when referring to the functions input/output values. Would that clear this up?

For example
```purescript
class Functor (Function inputType) where
  map :: forall originalOutputType newOutputType.
         (originalOutputType -> newOutputType) ->
         Function inputType originalOutputType -> 
         Function inputType newOutputType
  map originalToNew f = (\inputValue ->
    let originalOutputValue = f inputValue
    in originalToNew originalOutputValue)
```

**Comment by steven-zhc** [comment]
that's better, although more characters, but I think it's much easier to understand.

**Comment by steven-zhc** [comment]
Because I just read this page recently, I could modify them and send a merge request if you don't mind. :)

**Comment by JordanMartinez** [comment]
Please do! I likely won't get to it until tomorrow though.
