### ISSUE TITLE
Error on `Explaining-Kinds`

### ISSUE THREAD

**Issue by LiamGoodacre** [JordanMartinez/purescript-jordans-reference#44]
At the bottom it says:

> Either a b has kind Type -> Type -> Type ...

However, `Either a b` has kind `Type`, whereas `Either` has kind `Type -> Type -> Type`.

Perhaps examples could be added to the existing table?

| Type-level expression | Inferred kind |
|-|-:|
|`Unit`|`Type`|
|`Array Boolean`|`Type`|
|`Array`|`Type -> Type`|
|`Either Int String` | `Type`|
|`Either Int` | `Type -> Type`|
|`Either` | `Type -> Type -> Type`|
|`Record (foo :: Int)`|`Type`|
|`Record`|`# Type -> Type`|
|`(foo :: Int)`|`# Type`|
|...|...|

**Comment by JordanMartinez** [comment]
I put a variant of the table in the Basic Syntax folder: https://github.com/JordanMartinez/purescript-jordans-reference/commit/d1930fa88617d923f15f79ec9a4d1c47cd9df978

and the full table in Type-Level Syntax folder: https://github.com/JordanMartinez/purescript-jordans-reference/commit/c9d9b7fd1106f2ec7a636e243273f141ea29ad10
