### ISSUE TITLE
Change underlying language from Markdown to something else

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-jordans-reference#453]
For context, [this proposes other languages that might be easier to write in for documentation purposes](https://buttondown.email/hillelwayne/archive/please-dont-write-your-documentation-in-markdown/)

**Comment by thomashoneyman** [comment]
This may also be relevant: https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74

**Comment by JordanMartinez** [comment]
Mm... good point about Asciidoc. That's actually what I prefer over markdown (more power and flexibility), but I'm less familiar with it and, at the time of initially writing this, wasn't sure whether GH's support for it was a good as markdown. Looks like GH has better support now.

**Comment by JordanMartinez** [comment]
Closed by #511.
