### ISSUE TITLE
Maybe a typo in "Looping via Recursion"

### ISSUE THREAD

**Issue by StefanLiebig** [JordanMartinez/purescript-jordans-reference#466]
## Context

```
Section:
  Philosophical Foundations

Issue Type:
  Bug

Folder/File(s):
  - Philosophical Foundations/Looping via Recursion.md

```

## Body

In the section [Short-Circuiting](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/01-FP-Philosophical-Foundations/05-Looping-via-Recursion.md#short-circuiting) the `findFirst'` does not make sense to me (newbie). Shouldn´t it be just `findFirst`?

**Comment by JordanMartinez** [comment]
Yup! That's a typo! Thanks for bringing it to my attention!

>
