### ISSUE TITLE
"Type Level Programming" and  "Application-Structure"  section order should be swapped

### ISSUE THREAD

**Issue by gsantandrea** [JordanMartinez/purescript-jordans-reference#470]
Section:
  Hello World

Issue Type:
  Bug

Folder/File(s):
  - Hello-World/Application-Structure
  - Hello-World/Type Level Programming

The prefaction of " Application Structure" section states that type level programming is a prerequisite, but "Type Level Programming" appears after that in the order of "Hello world" sections.

**Comment by JordanMartinez** [comment]
Thanks for bringing this to my attention. It's possible I already fixed this in the `development` branch. That PR is pending the upcoming PS 0.14 release.
