### ISSUE TITLE
MonadEffect is not about monads not composing

### ISSUE THREAD

**Issue by hdgarrood** [JordanMartinez/purescript-jordans-reference#473]
```
Section:
  Hello World

Issue Type:
  Bug

Folder/File(s):
  - Hello World/Effect and Aff
```

In the Aff guide, you make a number of references to it not being possible to use `Effect.Console.log` in Aff because monads don't compose. This is not the real reason; the real reason is just that Effect and Aff are different types.

When people say monads don't compose, what they mean is that given the type

```purescript
newtype Compose f g a = Compose (f (g a))
```

while it is possible to define instances
```purescript
instance functorCompose :: (Functor f, Functor g) => Functor (Compose f g)
instance applicativeCompose :: (Applicative f, Applicative g) => Applicative (Compose f g)
```
it is not possible to define
```purescript
instance bindCompose :: (Bind f, Bind g) => Bind (Compose f g)
````
Let's try to write it:
```purescript
bindCompose :: forall f g a b. Compose f g a -> (a -> Compose f g b) -> Compose f g b
bindCompose (Compose fga) f' =
  -- for clarity, unwrap the result of `f` to get rid of `Compose`
  let
    f :: a -> f (g b)
    f = un Compose <<< f'
  {-
  So now we have:
    x :: f (g a)
    f :: a -> f (g b)
  And we need an f (g b).
  Let's try using `bind` twice to get the `a` out, and then applying `f`
  -}
  in
  Compose $ fga >>= \(ga :: g a) ->
    ga >>= \(a :: a) ->
      f a
```
This results in an error:
```
  Could not match type
    f2
  with type
    g0

while trying to match type f2 (g0 b3)
  with type g0 t1
while checking that expression f a
  has type g0 t1
```
So the problem is that the return type of `f` is `f (g b)`, but since we are inside a `>>=` for `g`, we need to return a `g _`, not an `f _`. Perhaps we can try adding a `pure`:
```patch
-      f a
+      pure (f a)
```
Unfortunately that fails with a similar error, "Could not match type g2 with type f0". What's going on now? Well `pure (f a)` has type `g (f (g b)`, which means that the inner bind now evaluates to something of type `g (f (g b)`, which means that the outer bind is now failing to typecheck since we need to return an `f _` from the outer bind. Let's add another `pure`:
```patch
  Compose $ fga >>= \(ga :: g a) ->
-    ga >>= \(a :: a) ->
+    pure $ ga >>= \(a :: a) ->
      pure (f a)
```
Now we get "Could not match type f0 (g1 b2) with type b2". Why's that? Well, the type we've ended up with is actually `f (g (f (g b)))`, when we really wanted just `f (g b)`. The issue is that we can't go from `f (g (f (g b)))` to the type we want without a way of swapping the order of the applications over.
That is, if we could swap over the middle `g` and `f`, we would have `f (f (g (g b)`, and from there, `join` lets us go from `m (m a)` to `m a`, so we can go from `f (f (g (g b)))` to `f (g b)` via `map join <<< join`. But Bind does not give us a way of writing `f (g a) -> g (f a)`. For that, we need something stronger, like Distributive: https://pursuit.purescript.org/packages/purescript-distributive/4.0.0/docs/Data.Distributive#t:Distributive

See https://stackoverflow.com/questions/7040844/applicatives-compose-monads-dont for more information about the idea that monads don't compose.

**Comment by JordanMartinez** [comment]
Thanks for the correction @hdgarrood!
