### ISSUE TITLE
Parallel instance for monad stack

### ISSUE THREAD

**Issue by leomayleomay** [JordanMartinez/purescript-jordans-reference#476]
## Context

Section:

Design Pattern

Issue Type:

Enhancement

Folder/File(s):

https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/22-Projects/src/01-Libraries/Parallel/11-Instance-for-Parallel.purs

hi @JordanMartinez, thanks a lot for coming up with such a great resource, for the Parallel instance, would you please add an example for monad stack like

```
newtype AppM a
  = AppM (ReaderT Env (StateT (Array Business) Aff) a)
```

cheers

**Comment by JordanMartinez** [comment]
As far as I can tell, you can't make an instance for that. `StateT` doesn't have a `Parallel` instance in [the list of instances under `Parallel`](https://pursuit.purescript.org/packages/purescript-parallel/4.0.0/docs/Control.Parallel.Class#t:Parallel), nor [in its own definition](https://pursuit.purescript.org/packages/purescript-transformers/4.2.0/docs/Control.Monad.State.Trans#t:StateT). 

And that makes sense when you think about it. `parallel` says "these two computations can be done in any order, just as long as both are done by the end." `StateT` says, "I reduce boilerplate for you by threading the state through multiple computations. However, state modification at Step 2 is dependent upon what the state was in Step 1." Thus, it must be sequential. 
If you wanted something state-like that allows parallel usage, you could probably use `AVar`.

**Comment by leomayleomay** [comment]
@JordanMartinez cheers, will give `AVar` or `Ref` a try, do you reckon it's a good idea to have the `AVar` or `Ref` stored in `Env`?

**Comment by JordanMartinez** [comment]
It's either that or passing it around things via an argument.

**Comment by JordanMartinez** [comment]
It sounds like your question has been answered, so I'll close this.

**Comment by leomayleomay** [comment]
@JordanMartinez cheers :)
