### ISSUE TITLE
Type of `log` is `String -> Effect Unit`, not just `Effect Unit`, in a comment in 02-Hello-World.purs

### ISSUE THREAD

**Issue by code-hunger** [JordanMartinez/purescript-jordans-reference#488]
Hello, sorry to discard the issue template but I believe this issue is too tiny to deserve all of that.

Here's the line I'm talking about:
https://github.com/JordanMartinez/purescript-jordans-reference/blob/4070f4c0f2a9da06e764c3cdb3235ede2b51bfde/21-Hello-World/02-Effect-and-Aff/src/01-Effect/02-Hello-World.purs#L8

The type of the `log` function is `log :: String -> Effect Unit`.
(https://pursuit.purescript.org/packages/purescript-console/4.1.0/docs/Effect.Console)
I'd happily open a PR, but I guess it'd be an overkill for such a trivial change.

**Comment by JordanMartinez** [comment]
Oh, whoops! Thanks for pointing this out. Does this bug still appear in the `v0.14-syntax` branch?

I agree that it's not worth all the boilerplate from the issue template.

**Comment by code-hunger** [comment]
Yes, here's the same line in the `v0.14-syntax` branch:

https://github.com/JordanMartinez/purescript-jordans-reference/blob/5df3f03195e8485aa09d28cbc0cf076c8e7b839a/21-Hello-World/02-Effect-and-Aff/src/01-Effect/02-Hello-World.purs#L8

Both links reference the specific (at that time, latest) commit in the respective branch when I visited the page on github so the previews here won't update when a fix is applied.

**Comment by JordanMartinez** [comment]
Ok. Thanks for investigating that. I'll fix this on that branch.
