### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#491]
https://github.com/JordanMartinez/purescript-jordans-reference/blob/4070f4c0f2a9da06e764c3cdb3235ede2b51bfde/11-Syntax/03-Type-Level-Programming-Syntax/src/02-Basic-Syntax/04-Reflection.purs#L43
I belive this should be `yesK and noK`

**Comment by JordanMartinez** [comment]
Yup. That's a typo. Thanks for reporting it!
