### ISSUE TITLE
Example is confusing because it doesn't compile

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#492]
https://github.com/JordanMartinez/purescript-jordans-reference/blame/latestRelease/11-Syntax/03-Type-Level-Programming-Syntax/src/02-Basic-Syntax/03-Defining-Functions/ReadMe.md#L197

**Comment by JordanMartinez** [comment]
Thanks for reporting.

I should better clarify that the code doesn't compile and tries to communicate the general idea.

**Comment by JordanMartinez** [comment]
@ursi Was this issue satisfactorily resolved in latest release now that #502 has been merged? To see the current state, go to this [header](https://github.com/JordanMartinez/purescript-jordans-reference/tree/latestRelease/11-Syntax/03-Type-Level-Programming-Syntax/src/02-Basic-Syntax/03-Defining-Functions#prolog-links) and scroll up slightly.

**Comment by JordanMartinez** [comment]
Actually, I'll close this now and let `ursi` reopen if he/she thinks it hasn't been resolved.

**Comment by ursi** [comment]
Looking at that section I found a typo. Fixed it in #506

**Comment by ursi** [comment]
I think I wan't clear about what I found confusing, because now I find the `-- Pseudo-code: this does not compile` a little bit confusing. Before, we had
```purescript
type ExampleCons = Cons
  first String (tail :: (second :: Int))
  (first :: String, second :: Int)
```
When I went into the REPL and did
```
:kind Cons first String (tail :: (second :: Int)) (first :: String, second :: Int)
``` 
it wouldn't work (This is what I was getting at when I said it wouldn't "compile", perhaps I should have been more clear.). I also found this very confusing because they ways `Cons` was being used here didn't seem to match with the documentation at all.

Now we've changed it to
```purescript
-- Pseudo-code: this does not compile
Cons "first" String () (first :: String)
```
But I think this is rather confusing because I wouldn't consider it pseudo-code. If I run
```
:kind Cons "first" String () (first :: String)
```
in the REPL it works just fine.

**Comment by JordanMartinez** [comment]
Ah.... I didn't think about using `:k` from the REPL. That would have been a better way to show that this "compiles" since that was the main issue I had.

**Comment by JordanMartinez** [comment]
Looks like the REPL won't complain even if I give it an invalid relationship:
```
$ spago repl
PSCi, version 0.13.8
Type :? for help

import Prelude

> import Prim.Row
> :kind Cons "first" String () (notFirst :: String)
Type
```

**Comment by JordanMartinez** [comment]
How about this? 
https://github.com/JordanMartinez/purescript-jordans-reference/commit/9d3fe804f248684102437e63cbf154f89b78652e

**Comment by ursi** [comment]
seems fine to me 👍
