### ISSUE TITLE
Suggestion: SICP book for "Lazy vs Strict" chapter

### ISSUE THREAD

**Issue by toraritte** [JordanMartinez/purescript-jordans-reference#499]
## Context

1. **Section**:   Philosophical Foundations

2. **Issue Type**: ToResearch

3. **Folder/file(s)**: [Philosophical Foundations/Lazy vs Strict](https://github.com/JordanMartinez/purescript-jordans-reference/blob/v0.14.0-syntax/01-FP-Philosophical-Foundations/04-Lazy-vs-Strict.md)

## Body

The book **Structure and Interpretation of Computer Programs (SICP)** (see [this](https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book.html) or [that](https://sarabander.github.io/sicp/)) has [a chapter on lazy evaluation and thunks](https://sarabander.github.io/sicp/html/4_002e2.xhtml) that I found really helpful - but it uses Lisp in the entire book... Hope you'll find it useful. (Couldn't find this publication mentioned in the issues and pull requests but if I do missed it, I'm sorry.)

**Comment by JordanMartinez** [comment]
I've summarized a few posts on Haskell's laziness in [purescript-to-haskell](https://github.com/JordanMartinez/purescript-to-haskell/blob/master/02-Syntax/07-Lazy-by-Default.md). I haven't read the above book, but I've heard of it.

Would my summary and links to those articles suffice?

**Comment by JordanMartinez** [comment]
Oh, I think you were saying I should include a link to the above book's chapter and potentially write my own summary of it in this repo.

**Comment by toraritte** [comment]
Oh, yes, the latter - sorry for being ambiguous. Just a link suggestion if someone wants to explore further. It's a really good book, but it only uses Lisp so that's a big overhead; especially that people reading your repo are probably new to purescript and FP in general, like me.

Long story short, do as you please, just wanted to put it out there. And thanks again for this project!
