### ISSUE TITLE
. can be used in operators as well

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#501]
https://github.com/JordanMartinez/purescript-jordans-reference/blob/4070f4c0f2a9da06e764c3cdb3235ede2b51bfde/11-Syntax/01-Basic-Syntax/src/02-Data-and-Functions/11-Infix-Notation/01-Regular.purs#L43

**Comment by JordanMartinez** [comment]
Looks like `.` can be used, but only if it's used alongside of other symbols. For example, this code doesn't compile on try.ps.ai:
```purescript
module Main where

import Prelude

import Effect (Effect)
import TryPureScript (p)

fun :: Int -> Int
fun x = x + 5 * 4

infixl 4 fun as .

main :: Effect Unit
main =
    render $ fold
      [ p (text "Try out the examples below, or create your own!")
      ]
```
However, changing `.` to `..` does compile.

I'm now wondering if there are other similar symbols where they will fail if used alone but succeed if used in combination with others.
