### ISSUE TITLE
Broken links in table-of-contents.md

### ISSUE THREAD

**Issue by and-pete** [JordanMartinez/purescript-jordans-reference#507]
## Context

```
Section:
  /

Issue Type:
  Bug

Folder/File(s):
  - table-of-contents.md

```

## Body

Hi Jordan.

Each of the links in `table-of-contents.md` that refer to another file elsewhere within the repo appear to be currently broken.

Specifically, each link (that I've checked) refers to the non-existing branch `ps-013.x-v0.25.1`

For example:
```
https://github.com/JordanMartinez/purescript-jordans-reference/blob/ps-013.x-v0.25.1/00-Getting-Started/ReadMe.md
                                                                   ^^^^^^^^^^^^^^^^^^
```
It appears to be all of them.

Internal hash links to other parts of `table-of-contents.md` file (such as its in its own TOC at the top) are fine, however.

Cheers!

**Comment by JordanMartinez** [comment]
That was caused by a typo on my part when I regenerated the ToC. I'll be pushing a fix later today.

**Comment by JordanMartinez** [comment]
I've verified that this works again.
