### ISSUE TITLE
Enhancements - run examples, print, spago install

### ISSUE THREAD

**Issue by senorsmile** [JordanMartinez/purescript-jordans-reference#509]
## Context

```
Section:
  Syntax

Issue Type: 
  Enhancement 

Folder/File(s):
    Basic-Syntax/ps-0.14-syntax/01-Preliminary-Concepts/01-Value-Function-Data-Syntax.purs
    Hello-World/01-Prelude-ish/02-Prelude/02-Useful-Functions.md
```

## Body

I suggest adding more examples that can show more of the types actually being used.  This would help beginners get a better grasp of what is being taught.  

E.g. in 01-Value-Function-Data-Syntax, most of the defined names just err out. 
```
> import Syntax.Meta

> integer_value 
5

```
so far so good

```
> example1
Error found:
in module $PSCI
at <internal>:0:0 - 0:0 (line 0, column 0 - line 0, column 0)

  No type class instance was found for
                                                         
    Data.Show.Show Type_Used_In_Functions_Type_Signatures
                                                         

while applying a function eval
  of type Eval t1 => t1 -> Effect Unit
  to argument it
while checking that expression eval it
  has type Effect t0
in value declaration $main

where t0 is an unknown type
      t1 is an unknown type

See https://github.com/purescript/documentation/blob/master/errors/NoInstanceFound.md for more information,
or to contribute content related to this error.
```
I can see that there are some made up things that are trying to teach something. 
However, most of the examples here do something similar. 

The problem with producing more examples to actually show something that can be run at such an early level is that we've constrained ourselves on purpose, so as to not overwhelm the learner (i.e. not introduce too many things at once). 

If I go a little further, I run into an example that I assume is supposed to use console log, but uses a keyword print:
Hello-World/01-Prelude-ish/02-Prelude/02-Useful-Functions.md
```
> print (5 + 5) == print $ 5 + 5
Error found:
in module $PSCI
at :1:1 - 1:6 (line 1, column 1 - line 1, column 6)

  Unknown value print


See https://github.com/purescript/documentation/blob/master/errors/UnknownName.md for more information,
or to contribute content related to this error.


> print (5 + 5)
Error found:
in module $PSCI
at :1:1 - 1:6 (line 1, column 1 - line 1, column 6)

  Unknown value print
```

Searching around, I might find this module: https://pursuit.purescript.org/packages/purescript-formatting/1.0.5/docs/Text.Formatting

```
node@a25949420a23:~/hostdir/purescript-jordans-reference/11-Syntax/01-Basic-Syntax$ spago install Formatting
[error] The following packages do not exist in your package set:
[error]   - Formatting
node@a25949420a23:~/hostdir/purescript-jordans-reference/11-Syntax/01-Basic-Syntax$ spago install Formatting
[error] The following packages do not exist in your package set:
[error]   - Formatting
node@a25949420a23:~/hostdir/purescript-jordans-reference/11-Syntax/01-Basic-Syntax$ spago install Text.Formatting
[error] The following packages do not exist in your package set:
[error]   - Text.Formatting
```
Not sure how I even install this.  
The build tools section says
```
# Install a package from the package set to your project
spago install packageName1 packageName2 # ...
```

which perhaps could use a real life example of how to actually look up a package, convert its name to something spago can recognize, install and then use.

**Comment by JordanMartinez** [comment]
Thanks for opening this issue.

I'm a bit confused. Why are you reporting problems with the PureScript 0.14.x syntax (i.e. `Basic-Syntax/ps-0.14-syntax`) rather than the current syntax (i.e. `Basic-Syntax/src`)? The v0.14.x syntax folder only exists because the v0.14.0 PureScript release hasn't been made yet. So, running `spago repl` or `spago build` won't compile that program unless you have built the current `master` branch of PureScript. Even if you do, I'm not yet supporting `v0.14.0` syntax yet.

> If I go a little further, I run into an example that I assume is supposed to use console log, but uses a keyword print

`print` is not a keyword. My point behind that example is that the left-hand side (i.e. `print (5 + 5)`) is the same as writing the right-hand side (i.e. `print $ 5 + 5`).

To clarify, what parts of this repo have you read and which instructions have you followed up to this point?

**Comment by senorsmile** [comment]
> I'm a bit confused. Why are you reporting problems with the PureScript 0.14.x syntax (i.e. Basic-Syntax/ps-0.14-syntax) rather than the current syntax (i.e. Basic-Syntax/src)? 

That makes sense now.  Due to the structure of how things are organized, I see the numbers as being some order that I'm trying to follow.  I didn't realize that represented something different, nor that the the src/ directory there was the same content but already completed. 

> print is not a keyword. My point behind that example is that the left-hand side (i.e. print (5 + 5)) is the same as writing the right-hand side (i.e. print $ 5 + 5).

I think I get that, but how do I get that to run?  

> To clarify, what parts of this repo have you read and which instructions have you followed up to this point?

To be fair, I started near the end, went to the middle a bit, then started from the beginning to be thorough.  I have zero background in Javascript, but am a long time "advanced beginner" of Haskell.

**Comment by JordanMartinez** [comment]
> Due to the structure of how things are organized, I see the numbers as being some order that I'm trying to follow. I didn't realize that represented something different, nor that the the src/ directory there was the same content but already completed.

Yeah, I was trying to get a new release out quickly without typing up every loose end (e.g. telling the reader to ignore that folder unless they want to see what the PureScript v0.14.0 syntax will look like). See [this comment](https://github.com/JordanMartinez/purescript-jordans-reference/issues/480#issuecomment-640234262) for context.

**Comment by JordanMartinez** [comment]
> I think I get that, but how do I get that to run?

Ah, ok. You'll need to `cd` into `11-Syntax/01-Basic-Syntax` and run `spago install` and then `spago repl`. `print` isn't an actual function, so you could use `identity` instead: `identity (5 + 5)` and `identity $ 5 + 5`.

```purescript
identity :: forall a. a -> a
identity x = x
```

**Comment by senorsmile** [comment]
Awesome!  Thanks for taking your time to answer my silly questions/recommendations.  I plan to dive deep into Purescript to learn web dev, since I need to tackle a new project and have zero interest learning JS (although I suspect I may be going down a path not well worn).  

I am hopeful to be able to contribute back here with hopefully useful PR's rather than just questions.

**Comment by JordanMartinez** [comment]
> I am hopeful to be able to contribute back here with hopefully useful PR's rather than just questions.

I look forward to it.
