### ISSUE TITLE
Potential confusing trap in REPL section

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#522]
to quote a post in `#purescript-beginners` on the FP slack
> Even the REPL instructions in Jordon's reference (which explicitly is for newcomers) omits stuff like importing Prelude (which results in me getting the "Unknown Operator (+)" error when doing a simple addition)

As you may know, just running `spago repl` (as per the instructions here) *should* import `Prelude` for you, but for this person it didn't. what happened? Well they were running it from a directory that contained a spago project that had its `.purs-repl` deleted (it was a friend's project). Turns out, when this is the case, the default one that imports `Prelude` for you is not used, you just get nothing, so they were pretty unsatisfied with the guide, as they felt like a very important instruction was left out (having to import the prelude for anything to work).

I think we should expand the instructions to mention something about either moving to a new directory and running `spago init` or making sure you're not already in a directory of a spago project before running `spago repl`.

**Comment by JordanMartinez** [comment]
The immediate issue is that the person did not realize they were in another directory entirely. So, whether a `.purs-repl` file exists or not, we should clarify that `Prelude` is imported by default via the `.purs-repl` file so the expression `5+5` should output 10. If instead they get an error when they run that, we should instruct them to import Prelude within their repl session and check their directory.

I believe I do talk about the `.purs-repl` file somewhere in that guide, but I don't think it was as visible/findable in this situation as it should have been.
