### ISSUE TITLE
Add documentation for String/Char escape sequences

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#523]
Things to cover
- everything [here](https://pursuit.purescript.org/builtins/docs/Prim)
- string escape sequences (unicode is `\x`, not `\u`, did you know that? I didn't)
- a decimal point separates `Int`s from `Number`s
- `1_000_000` syntax for `Int`s and `Numbers`
- anything else regarding literals that I either don't know or didn't remember at the time of writing.

**Comment by JordanMartinez** [comment]
I think the decimal point and the `1_000_000` syntax are already both covered here (https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/11-Syntax/01-Basic-Syntax/src/01-Preliminary-Concepts/03-The-Prim-Module.purs) as well as a few of the things in your above link. I'm not sure I should reproduce everything in the above link as that can change with compiler releases and it would be better to fix it on the compiler side in the first place.

The `->`/`Function` type alias is covered here: https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/11-Syntax/01-Basic-Syntax/src/02-Data-and-Functions/02-Function-Currying.purs

I also didn't know about the string escape sequences. I think I read about them in the release notes for `v0.13.0`, but didn't document it at the time.

**Comment by ursi** [comment]
Oh nice! I somehow managed to miss the Prim module when searching. So I guess the only thing that is left out is the other valid escape sequences (`\x` is documented) and the fact that they can be used to make `Char`s as well?

**Comment by JordanMartinez** [comment]
Sounds right.
