### ISSUE TITLE
Populate URL in repo's "About" section

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-jordans-reference#525]
Click on the settings/gears button and paste your URL
https://jordanmartinez.github.io/purescript-jordans-reference-site/

Example outcome:
![image](https://user-images.githubusercontent.com/3578681/98276646-20e7c300-1f4b-11eb-9456-3b2b94323393.png)
https://github.com/purescript-halogen/purescript-halogen

**Comment by JordanMartinez** [comment]
Done. Thanks!
