### ISSUE TITLE
Link down on typeclasses section

### ISSUE THREAD

**Issue by alarbada** [JordanMartinez/purescript-jordans-reference#530]
## Context

```
Syntax
Broken Link
File: 03-TypeClasses-and-Newtypes/03-Dictionaries--How-Type-Classes-Work.purs
```

## Body

> Dictionaries are what enable a function/value to magically appear in the
implementation of a function's body. The below code is a summary of
this article about type class 'dictionaries':
https://www.schoolofhaskell.com/user/jfischoff/instances-and-dictionaries
I could not explain it clearer nor more concisely than they did.

The link is down, and I'd love to know more about it. I'd like to provide solutions myself, but I'm just too much inexperienced to provide good posts about this theme.

Any alternatives?

(btw, thanks for this repo, it's helping me quite a bit with ps :smile:)

**Comment by JordanMartinez** [comment]
Ah... that's unfortunate.

Use the Internet Archive to bring it back: https://web.archive.org/web/20200116160958/https://www.schoolofhaskell.com/user/jfischoff/instances-and-dictionaries

And I'm glad it's been helping!
