### ISSUE TITLE
Does not include all possible character for infix operators 

### ISSUE THREAD

**Issue by ursi** [JordanMartinez/purescript-jordans-reference#532]
https://github.com/JordanMartinez/purescript-jordans-reference/blob/0e5601bb5b2fbc6d37fd9e282887a8f32c19d67c/11-Syntax/01-Basic-Syntax/src/06-Infix-Notation/01-Regular.purs#L43

recently somone pointed me to this bit of compiler code which outlines exactly which characters are legal.
https://github.com/purescript/purescript/blob/48634d05da1021ac1bcb4907461ae9b2d3b0e699/lib/purescript-cst/src/Language/PureScript/CST/Lexer.hs#L659
I haven't looked in to exactly what this includes yet. But I'm pretty sure it's a good amount of unicode characters.

**Comment by JordanMartinez** [comment]
Looks like `isSymbol` refers to [`isSymbol`](https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Char.html#v:isSymbol), where it clarifies that it's either one of these symbols [as defined in Unicode](https://www.unicode.org/reports/tr44/tr44-14.html#GC_Values_Table):
- MathSymbol
- CurrencySymbol
- ModiferSymbol
- OtherSymbol

**Comment by JordanMartinez** [comment]
To fix this bug, we'll need to clarify that the symbols can be:
- one of these characters: `:!#$%&*+./<=>?@\\^|-~`
- or one of the symbols defined in the above Unicode categories.

For the unicode category, we should probably provide an example of each one.
