### ISSUE TITLE
Missing functional dependency in example about functional dependencies

### ISSUE THREAD

**Issue by simonolander** [JordanMartinez/purescript-jordans-reference#557]
https://github.com/JordanMartinez/purescript-jordans-reference/blob/6d634d6cb0c3bc9135c90fbb6cc91fdc6d39856b/11-Syntax/01-Basic-Syntax/src/11-TypeClasses/08-Functional-Dependencies.purs#L36

It appears to me that the referenced line rather should be the following:
```purescript
class Unwrap a b | a -> b where
```

**Comment by JordanMartinez** [comment]
Yup, that's correct. Thanks for bringing it to my attention.
