### ISSUE TITLE
Type variable in function implementation of Applicative (OutputBox input) 

### ISSUE THREAD

**Issue by MitinPavel** [JordanMartinez/purescript-jordans-reference#564]
## Context

1. Indicate the affected section (i.e. top-level folder)

Hello-World

2. Indicate what kind of issue this is

Bug

3. If it applies, indicate the file to which you are referring using non-numerical-ordering names

"Hello World/Application-Structure/src/MTL/Foundations.md/Special Output.md"

## Bug

The instance of `Applicative (OutputBox input)` uses `a` type variable in the function implementation:

```
instance (Apply (OutputBox input)) <= Applicative (OutputBox input) where
  pure :: forall a. a -> (OutputBox input) a
  pure value = OutputBox (\input -> pure a)
```

Fix: https://github.com/MitinPavel/purescript-jordans-reference/commit/678b2b6e6675629cfe411a9fc49456b1db416287

Does it look like a bug and a fix? Can I create a PR for the fix?

**Comment by JordanMartinez** [comment]
Yup! That's bug. Thanks for bringing it up. Feel free to submit a PR!

**Comment by MitinPavel** [comment]
A pull-request has been created.

P.S. Thank you for a great tutorial.
