### ISSUE TITLE
Typo in The Function Monad

### ISSUE THREAD

**Issue by stiff** [JordanMartinez/purescript-jordans-reference#573]
## Context

Section:
   5.5.1.3.1.1. Hello-World Application-Structure 

Issue Type:
  Bug

Folder/File(s):
  - MTL/Foundations.md

Very similar to #435 just a little further down the text:

```purescript
class Functor (Function inputType) where
  map :: forall originalOutputType newOutputType.
         (originalOutputType -> newOutputType) ->
         Function inputType originalOutputType -> Function inputType newOutput
  map originalToNew f = (\input -> originalOutput $ f input)
  -- or
  map originalToNew f = (originalOutput <<< f)
  -- or even
  map = (<<<)
```

while there is no such thing as `originalOutput`, it's `originalToNew`.

**Comment by JordanMartinez** [comment]
Yeah, this is probably me copy-pasting that code over.
