### ISSUE TITLE
Typo in function signature

### ISSUE THREAD

**Issue by Masynchin** [JordanMartinez/purescript-jordans-reference#587]
## Context

1. Indicate the affected section (i.e. top-level folder)

Hello Word

2. Indicate what kind of issue this is

- [ ] Bug = a problem that needs to be corrected
- [ ] Enhancement = a new idea that can be documented/filed
- [ ] ToResearch = a link you want me to investigate
- [x] Typo

3. If it applies, indicate the file to which you are referring using ~~non-numerical-ordering names~~ link

Issue Type:
  Typo

Filepath:
  [This](https://github.com/JordanMartinez/purescript-jordans-reference/blob/0de8de5cfc0993fe56b00d617d9da80d474c282f/21-Hello-World/05-Application-Structure/src/02-MTL/02-Implementing-a-Monad-Transformer/01-Looking-at-OO-for-a-Pattern.md)

4. The Issue itself

`runNTimes` should have `Int -> (a -> a) -> a -> a` signature instead of existing `Int -> (a -> a) -> a`.

**Comment by JordanMartinez** [comment]
Thanks. Mind submitting a PR to fix that?

**Comment by Masynchin** [comment]
> Thanks. Mind submitting a PR to fix that?

Sure, I have already done it, but delete because issue should be created first :)
