### ISSUE TITLE
Example is confusing in data types

### ISSUE THREAD

**Issue by FurrySparkle** [JordanMartinez/purescript-jordans-reference#592]
## Context

1. Indicate the affected section (i.e. top-level folder)

Section 2 Philosophical principles, part 3 Data types

2. Indicate what kind of issue this is

Enhancement = a new idea that can be documented/filed

## Body
This example is vague and difficult to understand as a new dev. I have no idea how you mean to describe the immutability with the code and flow chart. I understand the wording at the beginning, but at the example it doesn't seem to apply. Maybe a more concrete or tangible example

**Comment by FurrySparkle** [comment]
More over, there isn't any primer for the foundations. Like PEMDAS math, and How types call or what int->int even means. These aren't apparent when coming from light exposure to irregular math of OO and impure functions. 

Maybe have a readability Primer doc explaining how to read the code examples of the foundational docs.

**Comment by JordanMartinez** [comment]
Hm... I think I see what you mean.

It would likely help to first define a linked list in code such as JavaScript. Then I could show a few values and what their corresponding visual would be in memory via flowcharts.

Then it would help to show how one "modifies" an immutable linked list by creating a copy. And then introduce the problem that additional work is done that isn't needed and persistence as a solution to that problem.
