### ISSUE TITLE
From Free to Run - link to 404

### ISSUE THREAD

**Issue by neilhan** [JordanMartinez/purescript-jordans-reference#602]
## Context

1. Indicate the affected section (i.e. top-level folder)
[From Free to Run](https://jordanmartinez.github.io/purescript-jordans-reference-site/content/21-Hello-World/05-Application-Structure/src/03-Free/03-From-Free-to-Run/index.html)

2. Indicate what kind of issue this is

Bug = "Free Programs, More Better Programs", the link is broken. Leads to 404.

**Comment by JordanMartinez** [comment]
Thanks!
Link should be: https://reasonablypolymorphic.com/blog/freer-monads/index.html

The current page's URL is being prepended to this one.

**Comment by neilhan** [comment]
Thank you. I really enjoy this repo. No-nonsense.
