### ISSUE TITLE
Understanding the Effect Monad. Erroneous example

### ISSUE THREAD

**Issue by JohnGurin** [JordanMartinez/purescript-jordans-reference#604]
```
Section:
  Hello-World

Issue Type:
  Bug

Folder/File(s):
  - Hello-World/Effect-and-Aff/src/Effect/Native-Side-Effects-via-Effect.md

```
```purescript
data Unit = Unit
unit :: Unit
unit = Unit

type PendingComputation a = (Unit -> a)
data Effect a = Box (PendingComputation a -> a)

unsafePerformEffect :: {- forall a. -} Effect a -> a
unsafePerformEffect (Box pendingComputation) = pendingComputation unit
--                                                                ^^^^
{-
 Could not match type

    Unit

  with type

    Unit -> a0
-}
```

[source](https://github.com/JordanMartinez/purescript-jordans-reference/blob/0de8de5cfc0993fe56b00d617d9da80d474c282f/21-Hello-World/02-Effect-and-Aff/src/01-Effect/01-Native-Side-Effects-via-Effect.md#understanding-the-effect-monad)

[try.purescript.org](https://try.purescript.org/?code=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAWACgSwkAXJOAVTRQrgF5b6KSSI24AuH1hp24s6g0sQC0EuAB84AQTgBjEMAAOEKhRQgMFbJSwooUOLqgBPOACN4eLllwY1SAM6uYYOOjjUABlwMfiQUFmrwAAowaGDoAOYAwqoaWjoY1CwAFKKMEgB8vgCUHJLScorkVHCuFPZKFBAEcPqGNSAErr5w4THxysmalGkAdGSU1ACiAGZTMPVdLABCIAAecJlRvWiJA6m6XflFJVKycAAq2CidXJh4SGqd%2BvCV1DV1DU0UIHBxMIxPJBOch6sW2-XUg20ugANHAIB5Ogxmt8VBCKPBqAA3JBQCAwaGAsq%2BGJwAgfNCIiidDrQCijcRcVxIWZRPBTdrAaazeZ8ODsu4mXzDOBcuaMaiHJBCJks-D8zkzMXrZZrEHxJJooa6QrMbrRUE7TVQjCBChAA)

As a suggestion
```purescript
import Prelude

unsafePerformEffect :: forall a. Semiring a => Effect a -> a
unsafePerformEffect (Box pendingComputation) = pendingComputation (\_ -> one)
```

**Comment by JordanMartinez** [comment]
The issue is here:
```diff
type PendingComputation a = (Unit -> a)
 -- expands to    Box (Unit -> a -> a)
-data Effect a = Box (PendingComputation a -> a)
 -- expands to    Box (Unit -> a)
+data Effect a = Box (PendingComputation a)
```
