### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by dboris** [JordanMartinez/purescript-jordans-reference#607]
Hi.
I'm looking for an offline version of these docs (pdf, epub, mobi) for reading on a kindle/kobo device. Do you know if such a version exists?
I've attempted to generate the mdbook site, but I get an error `Couldn't open SUMMARY.md`. I couldn't find instructions how to generate the mdbook site in the Readme.
Any pointers how to proceed would be appreciated.

**Comment by JordanMartinez** [comment]
Run `mdbook` on https://github.com/JordanMartinez/purescript-jordans-reference-site

This repo stores the source files whereas that one is used to build the website. I thought it would have less clutter that way.

**Comment by JordanMartinez** [comment]
See also: https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/.procedures/redeploy-book.sh

**Comment by dboris** [comment]
Thank you.
